# Generated by Django 2.2.12 on 2020-05-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_charts', '0003_auto_20190201_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartjsbarmodel',
            name='option_barShowStroke',
            field=models.BooleanField(blank=True, default=True, verbose_name='Stroke on each bar'),
        ),
        migrations.AlterField(
            model_name='chartjsbarmodel',
            name='option_scaleBeginAtZero',
            field=models.BooleanField(blank=True, default=True, verbose_name='Scale should start at zero, or an order of magnitude down from the lowest value'),
        ),
        migrations.AlterField(
            model_name='chartjsbarmodel',
            name='option_scaleShowGridLines',
            field=models.BooleanField(blank=True, default=True, verbose_name='Grid lines are shown across the chart'),
        ),
        migrations.AlterField(
            model_name='chartjsbarmodel',
            name='option_scaleShowHorizontalLines',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show horizontal lines (except X axis)'),
        ),
        migrations.AlterField(
            model_name='chartjsbarmodel',
            name='option_scaleShowVerticalLines',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show vertical lines (except Y axis)'),
        ),
        migrations.AlterField(
            model_name='chartjsdoughnutmodel',
            name='option_animateRotate',
            field=models.BooleanField(blank=True, default=True, verbose_name='Animate the rotation of the Chart'),
        ),
        migrations.AlterField(
            model_name='chartjsdoughnutmodel',
            name='option_animateScale',
            field=models.BooleanField(blank=True, default=False, verbose_name='Animate scaling the Doughnut from the centre'),
        ),
        migrations.AlterField(
            model_name='chartjsdoughnutmodel',
            name='option_segmentShowStroke',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show a stroke on each segment'),
        ),
        migrations.AlterField(
            model_name='chartjsglobalsettingsmodel',
            name='animation',
            field=models.BooleanField(blank=True, default=True, verbose_name='Animate the chart'),
        ),
        migrations.AlterField(
            model_name='chartjsglobalsettingsmodel',
            name='enable',
            field=models.BooleanField(blank=True, default=True, verbose_name='Enable Global Settings'),
        ),
        migrations.AlterField(
            model_name='chartjsglobalsettingsmodel',
            name='maintainAspectRatio',
            field=models.BooleanField(blank=True, default=True, verbose_name='Maintain the starting aspect ratio when responsive'),
        ),
        migrations.AlterField(
            model_name='chartjsglobalsettingsmodel',
            name='responsive',
            field=models.BooleanField(blank=True, default=False, verbose_name='Chart should be responsive and resize when the browser does.'),
        ),
        migrations.AlterField(
            model_name='chartjsglobalsettingsmodel',
            name='scaleBeginAtZero',
            field=models.BooleanField(blank=True, default=False, verbose_name='Scale should start at zero'),
        ),
        migrations.AlterField(
            model_name='chartjsglobalsettingsmodel',
            name='scaleIntegersOnly',
            field=models.BooleanField(blank=True, default=True, verbose_name='Scale should stick to integers, not floats'),
        ),
        migrations.AlterField(
            model_name='chartjsglobalsettingsmodel',
            name='scaleOverride',
            field=models.BooleanField(blank=True, default=False, verbose_name='Override with a hard coded scale'),
        ),
        migrations.AlterField(
            model_name='chartjsglobalsettingsmodel',
            name='scaleShowLabels',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show labels on the scale'),
        ),
        migrations.AlterField(
            model_name='chartjsglobalsettingsmodel',
            name='showScale',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show the scale'),
        ),
        migrations.AlterField(
            model_name='chartjsglobalsettingsmodel',
            name='showTooltips',
            field=models.BooleanField(blank=True, default=True, verbose_name='Draw tooltips on the canvas'),
        ),
        migrations.AlterField(
            model_name='chartjslinemodel',
            name='option_bezierCurve',
            field=models.BooleanField(blank=True, default=True, verbose_name='Line is curved between points'),
        ),
        migrations.AlterField(
            model_name='chartjslinemodel',
            name='option_datasetFill',
            field=models.BooleanField(blank=True, default=True, verbose_name='Fill the dataset with a colour'),
        ),
        migrations.AlterField(
            model_name='chartjslinemodel',
            name='option_datasetStroke',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show a stroke for datasets'),
        ),
        migrations.AlterField(
            model_name='chartjslinemodel',
            name='option_pointDot',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show a dot for each point'),
        ),
        migrations.AlterField(
            model_name='chartjslinemodel',
            name='option_scaleShowGridLines',
            field=models.BooleanField(blank=True, default=True, verbose_name='Grid lines are shown across the chart'),
        ),
        migrations.AlterField(
            model_name='chartjslinemodel',
            name='option_scaleShowHorizontalLines',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show horizontal lines (except X axis)'),
        ),
        migrations.AlterField(
            model_name='chartjslinemodel',
            name='option_scaleShowVerticalLines',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show vertical lines (except Y axis)'),
        ),
        migrations.AlterField(
            model_name='chartjspiemodel',
            name='option_animateRotate',
            field=models.BooleanField(blank=True, default=True, verbose_name='Animate the rotation of the Chart'),
        ),
        migrations.AlterField(
            model_name='chartjspiemodel',
            name='option_animateScale',
            field=models.BooleanField(blank=True, default=False, verbose_name='Animate scaling the Doughnut from the centre'),
        ),
        migrations.AlterField(
            model_name='chartjspiemodel',
            name='option_segmentShowStroke',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show a stroke on each segment'),
        ),
        migrations.AlterField(
            model_name='chartjspolarmodel',
            name='option_animateRotate',
            field=models.BooleanField(blank=True, default=True, verbose_name='Animate the rotation of the chart'),
        ),
        migrations.AlterField(
            model_name='chartjspolarmodel',
            name='option_animateScale',
            field=models.BooleanField(blank=True, default=False, verbose_name='Animate scaling the chart from the centre'),
        ),
        migrations.AlterField(
            model_name='chartjspolarmodel',
            name='option_scaleBeginAtZero',
            field=models.BooleanField(blank=True, default=True, verbose_name='Scale should begin at zero'),
        ),
        migrations.AlterField(
            model_name='chartjspolarmodel',
            name='option_scaleShowLabelBackdrop',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show a backdrop to the scale label'),
        ),
        migrations.AlterField(
            model_name='chartjspolarmodel',
            name='option_scaleShowLine',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show line for each value in the scale'),
        ),
        migrations.AlterField(
            model_name='chartjspolarmodel',
            name='option_segmentShowStroke',
            field=models.BooleanField(blank=True, default=True, verbose_name='Stroke a line around each segment in the chart'),
        ),
        migrations.AlterField(
            model_name='chartjsradarmodel',
            name='option_angleShowLineOut',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show the angle lines out of the radar'),
        ),
        migrations.AlterField(
            model_name='chartjsradarmodel',
            name='option_datasetFill',
            field=models.BooleanField(blank=True, default=True, verbose_name='Fill the dataset with a colour'),
        ),
        migrations.AlterField(
            model_name='chartjsradarmodel',
            name='option_datasetStroke',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show a stroke for datasets'),
        ),
        migrations.AlterField(
            model_name='chartjsradarmodel',
            name='option_pointDot',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show a dot for each point'),
        ),
        migrations.AlterField(
            model_name='chartjsradarmodel',
            name='option_scaleBeginAtZero',
            field=models.BooleanField(blank=True, default=True, verbose_name='Scale should begin at zero'),
        ),
        migrations.AlterField(
            model_name='chartjsradarmodel',
            name='option_scaleShowLabels',
            field=models.BooleanField(blank=True, default=False, verbose_name='Show labels on the scale'),
        ),
        migrations.AlterField(
            model_name='chartjsradarmodel',
            name='option_scaleShowLine',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show lines for each scale point'),
        ),
    ]
