# Generated by Django 2.2.16 on 2020-10-12 22:19

from django.db import migrations, models
import warnings
from django.conf import settings
import json


default_chart_colors = [
    "rgb(151,187,205)",
    "rgb(220,220,220)",
    "rgb(247,70,74)",
    "rgb(70,191,189)",
    "rgb(253,180,92)",
    "rgb(148,159,177)",
    "rgb(77,83,96)",
    "rgb(255,255,255)",
]


# Mapping from CMS Plugin Filer Image > DjangoCMS Picture
array_color_options = [
    "Chart.defaults.global.elements.arc.backgroundColor",
    "Chart.defaults.global.elements.line.borderColor",
    "Chart.defaults.global.elements.point.backgroundColor",
    "Chart.defaults.global.elements.rectangle.backgroundColor",
]

single_value_color_options = [
    "Chart.defaults.global.elements.line.backgroundColor",
]



def add_default_formats(apps, schema_editor):
    warnings.warn(
        "CAUTION - this adds the default ChartJS SASS (deprecated) default colors"
        " to DjangoCMS Charts for ChartJS ver 2.x ")

    GlobalOptionsGroupModel = apps.get_model('djangocms_charts', 'globaloptionsgroupmodel')
    GlobalOptionsModel = apps.get_model('djangocms_charts', 'globaloptionsmodel')

    global_options_group = GlobalOptionsGroupModel(enabled=True,
                                                   name='Default Global Settings',
                                                   site_id=settings.SITE_ID)
    global_options_group.save()

    for arr_opt in array_color_options:
        opt = GlobalOptionsModel(options_group =global_options_group,
                                 label=arr_opt,
                                 type='json',
                                 value=json.dumps(default_chart_colors)).save()

    for val_opt in single_value_color_options:
        opt = GlobalOptionsModel(options_group=global_options_group,
                                 label=val_opt,
                                 type='text',
                                 value=default_chart_colors[0]).save()


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_charts', '0007_delete_old_charts'),
    ]

    operations = [
        migrations.RunPython(add_default_formats, reverse_code=migrations.RunPython.noop)


    ]
