# Generated by Django 2.2.16 on 2020-11-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_charts', '0009_remove_old_charts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axisoptionsgroupmodel',
            name='type',
            field=models.CharField(blank=True, choices=[('linear', 'linear'), ('logarithmic', 'logarithmic'), ('category', 'category'), ('time', 'time'), ('radial', 'radial')], max_length=30, null=True, verbose_name='Axis Type'),
        ),
        migrations.AlterField(
            model_name='axisoptionsmodel',
            name='type',
            field=models.CharField(default='text', help_text='Select the input data type', max_length=30, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='chartoptionsmodel',
            name='type',
            field=models.CharField(default='text', help_text='Select the input data type', max_length=30, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='chartspecificoptionsmodel',
            name='type',
            field=models.CharField(default='text', help_text='Select the input data type', max_length=30, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='datasetoptionsmodel',
            name='type',
            field=models.CharField(default='text', help_text='Select the input data type', max_length=30, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='datasetspecificoptionsmodel',
            name='type',
            field=models.CharField(default='text', help_text='Select the input data type', max_length=30, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='globaloptionsmodel',
            name='type',
            field=models.CharField(default='text', help_text='Select the input data type', max_length=30, verbose_name='Data Type'),
        ),
    ]
