# Generated by Django 4.2.29 on 2026-03-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_charts', '0010_auto_20201106_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin'),
        ),
        migrations.AlterField(
            model_name='chartmodel',
            name='colors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_colors', to='djangocms_charts.colorgroupmodel'),
        ),
        migrations.AlterField(
            model_name='chartmodel',
            name='dataset_options_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_options', to='djangocms_charts.datasetoptionsgroupmodel'),
        ),
        migrations.AlterField(
            model_name='chartmodel',
            name='xAxis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_xAxis', to='djangocms_charts.axisoptionsgroupmodel'),
        ),
        migrations.AlterField(
            model_name='chartmodel',
            name='yAxis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_yAxis', to='djangocms_charts.axisoptionsgroupmodel'),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin'),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='colors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_colors', to='djangocms_charts.colorgroupmodel'),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='dataset_options_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_options', to='djangocms_charts.datasetoptionsgroupmodel'),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='xAxis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_xAxis', to='djangocms_charts.axisoptionsgroupmodel'),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='yAxis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_yAxis', to='djangocms_charts.axisoptionsgroupmodel'),
        ),
    ]
