# Generated by Django 4.2.30 on 2026-05-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_charts', '0011_alter_chartmodel_cmsplugin_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartmodel',
            name='chart_options_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_options', to='djangocms_charts.chartoptionsgroupmodel'),
        ),
        migrations.AlterField(
            model_name='chartmodel',
            name='colors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_colors', to='djangocms_charts.colorgroupmodel'),
        ),
        migrations.AlterField(
            model_name='chartmodel',
            name='dataset_options_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_options', to='djangocms_charts.datasetoptionsgroupmodel'),
        ),
        migrations.AlterField(
            model_name='chartmodel',
            name='xAxis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_xAxis', to='djangocms_charts.axisoptionsgroupmodel'),
        ),
        migrations.AlterField(
            model_name='chartmodel',
            name='yAxis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_yAxis', to='djangocms_charts.axisoptionsgroupmodel'),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='colors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_colors', to='djangocms_charts.colorgroupmodel'),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='dataset_options_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_options', to='djangocms_charts.datasetoptionsgroupmodel'),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='xAxis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_xAxis', to='djangocms_charts.axisoptionsgroupmodel'),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='yAxis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_yAxis', to='djangocms_charts.axisoptionsgroupmodel'),
        ),
    ]
